## Leonardo Sanchez Roncancio

# Caso 1

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/wikipedia-movie-plots/wiki_movie_plots_deduped.csv


In [4]:
df = pd.read_csv(os.path.join(dirname, filename))
df

Release Year                             Title Origin/Ethnicity  \
0              1901            Kansas Saloon Smashers         American   
1              1901     Love by the Light of the Moon         American   
2              1901           The Martyred Presidents         American   
3              1901  Terrible Teddy, the Grizzly King         American   
4              1902            Jack and the Beanstalk         American   
...             ...                               ...              ...   
34881          2014                 The Water Diviner          Turkish   
34882          2017                Çalgı Çengi İkimiz          Turkish   
34883          2017                      Olanlar Oldu          Turkish   
34884          2017                  Non-Transferable          Turkish   
34885          2017                İstanbul Kırmızısı          Turkish   

                                 Director  \
0                                 Unknown   
1                                 Unknown   
2                                 Unknown   
3                                 Unknown   
4      George S. Fleming, Edwin S. Porter   
...                                   ...   
34881             Director: Russell Crowe   
34882                      Selçuk Aydemir   
34883                         Hakan Algül   
34884                     Brendan Bradley   
34885                      Ferzan Özpetek   

                                                    Cast            Genre  \
0                                                    NaN          unknown   
1                                                    NaN          unknown   
2                                                    NaN          unknown   
3                                                    NaN          unknown   
4                                                    NaN          unknown   
...                                                  ...              ...   
34881  Director: Russell Crowe\r\nCast: Russell Crowe...          unknown   
34882                          Ahmet Kural, Murat Cemcir           comedy   
34883              Ata Demirer, Tuvana Türkay, Ülkü Duru           comedy   
34884  YouTubers Shanna Malcolm, Shira Lazar, Sara Fl...  romantic comedy   
34885  Halit Ergenç, Tuba Büyüküstün, Mehmet Günsür, ...         romantic   

                                               Wiki Page  \
0      https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...   
1      https://en.wikipedia.org/wiki/Love_by_the_Ligh...   
2      https://en.wikipedia.org/wiki/The_Martyred_Pre...   
3      https://en.wikipedia.org/wiki/Terrible_Teddy,_...   
4      https://en.wikipedia.org/wiki/Jack_and_the_Bea...   
...                                                  ...   
34881    https://en.wikipedia.org/wiki/The_Water_Diviner   
34882  https://en.wikipedia.org/wiki/%C3%87alg%C4%B1_...   
34883         https://en.wikipedia.org/wiki/Olanlar_Oldu   
34884  https://en.wikipedia.org/wiki/Non-Transferable...   
34885  https://en.wikipedia.org/wiki/%C4%B0stanbul_K%...   

                                                    Plot  
0      A bartender is working at a saloon, serving dr...  
1      The moon, painted with a smiling face hangs ov...  
2      The film, just over a minute long, is composed...  
3      Lasting just 61 seconds and consisting of two ...  
4      The earliest known adaptation of the classic f...  
...                                                  ...  
34881  The film begins in 1919, just after World War ...  
34882  Two musicians, Salih and Gürkan, described the...  
34883  Zafer, a sailor living with his mother Döndü i...  
34884  The film centres around a young woman named Am...  
34885  The writer Orhan Şahin returns to İstanbul aft...  

[34886 rows x 8 columns]

In [8]:
df.loc[10,"Plot"]

'The Rarebit Fiend gorges on Welsh rarebit at a restaurant. When he leaves, he begins to get dizzy as he starts to hallucinate. He desperately tries to hang onto a lamppost as the world spins all around him. A man helps him get home. He falls into bed and begins having more hallucinatory dreams. During a dream sequence, the furniture begins moving around the room. Imps emerge from a floating Welsh rarebit container and begin poking his head as he sleeps. His bed then begins dancing and spinning wildly around the room before flying out the window with the Fiend in it. The bed floats across the city as the Fiend floats up and off the bed. He hangs off the back and eventually gets caught on a weathervane atop a steeple. His bedclothes tear and he falls from the sky, crashing through his bedroom ceiling. The Fiend awakens from the dream after falling out of his bed.'

In [11]:
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

# 1. procesar el texto

In [13]:
# Preprocesamiento de texto
stop_words = set(stopwords.words('english'))  # stopwords en inglés
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Eliminar caracteres especiales y números
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Convertir a minúsculas
    text = text.lower()
    # Tokenización
    tokens = word_tokenize(text)
    # Eliminar stopwords 
    tokens = [word for word in tokens if word not in stop_words]
    # Unir tokens en una cadena de texto nuevamente
    preprocessed_text = ' '.join(tokens)
    return preprocessed_text

In [40]:
df['Processed_Plot'] = df['Plot'].apply(preprocess_text)
df.head()

Release Year                             Title Origin/Ethnicity  \
0          1901            Kansas Saloon Smashers         American   
1          1901     Love by the Light of the Moon         American   
2          1901           The Martyred Presidents         American   
3          1901  Terrible Teddy, the Grizzly King         American   
4          1902            Jack and the Beanstalk         American   

                             Director Cast    Genre  \
0                             Unknown  NaN  unknown   
1                             Unknown  NaN  unknown   
2                             Unknown  NaN  unknown   
3                             Unknown  NaN  unknown   
4  George S. Fleming, Edwin S. Porter  NaN  unknown   

                                           Wiki Page  \
0  https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...   
1  https://en.wikipedia.org/wiki/Love_by_the_Ligh...   
2  https://en.wikipedia.org/wiki/The_Martyred_Pre...   
3  https://en.wikipedia.org/wiki/Terrible_Teddy,_...   
4  https://en.wikipedia.org/wiki/Jack_and_the_Bea...   

                                                Plot  \
0  A bartender is working at a saloon, serving dr...   
1  The moon, painted with a smiling face hangs ov...   
2  The film, just over a minute long, is composed...   
3  Lasting just 61 seconds and consisting of two ...   
4  The earliest known adaptation of the classic f...   

                                      Processed_Plot  
0  bartender working saloon serving drinks custom...  
1  moon painted smiling face hangs park night you...  
2  film minute long composed two shots first girl...  
3  lasting seconds consisting two shots first sho...  
4  earliest known adaptation classic fairytale fi...

## 2. Vectorización de palabras (word embeddings) 

In [15]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import pandas as pd


# Tokenización de las sinopsis
tokenized_plots = [word_tokenize(plot) for plot in df['Processed_Plot']]

# Entrenamiento del modelo Word2Vec
embedding_size = 100  # Tamaño del espacio de embeddings
window_size = 5  # Tamaño de la ventana de contexto
min_word_count = 1  # Frecuencia mínima de palabra para ser considerada
sample = 1e-3  # Umbral de submuestreo
sg = 1  # Usar skip-gram

model = Word2Vec(sentences=tokenized_plots,
                 vector_size=embedding_size,
                 window=window_size,
                 min_count=min_word_count,
                 sample=sample,
                 sg=sg)

# Entrenamiento completado, ahora puedes utilizar los embeddings

# Ejemplo: Obtener el embedding para una palabra específica
word_embedding = model.wv['movie']
print("Embedding para la palabra 'movie':", word_embedding)

# Guardar el modelo entrenado para su uso posterior
model.save("movie_embeddings.model")

Embedding para la palabra 'movie': [-0.33506083  0.2870184  -0.01278507 -0.14145465 -0.6793263  -0.38114604
  0.44765913  0.06456455 -0.01792476 -0.96355283 -0.19723158  0.02235228
  0.06972686  0.4116224  -0.24720967  0.19974618  0.34716302 -0.0063852
 -0.41601646 -0.7017542  -0.14235716 -0.53588665 -0.46042362  0.04512292
 -0.2602801  -0.55583054  0.21210144 -0.41152546 -0.45846528 -0.05255209
  0.37542894 -0.16361514  0.35140836 -0.24902923 -0.21262518  0.03050536
  0.07108462 -0.21082969  0.00404053 -0.24132814  0.5321582  -0.00511878
  0.5705998  -0.00529599  0.5744228   0.05059044  0.28053823  0.55972314
  0.06068378  0.28022778  0.8824665   0.22759451  0.4115301  -0.20839562
  0.00788499 -0.00927596  0.19861905  0.15407577 -0.19684516  0.18389963
  0.54812306  0.2363442  -0.3416996  -0.42581934 -0.18114996  0.05205978
 -0.14864404 -0.2380347  -0.4037939   0.33752495 -0.67666125 -0.3570888
  0.5623688   0.04399182  0.00909979 -0.11234196  0.03979968  0.99843806
  0.34168333 -0.24

In [ ]:
# Cargar el modelo entrenado
# model = Word2Vec.load("movie_embeddings.model")

## 3. Calcular la similitud de las sinopsis con similitud coseno

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

# Obtener los embeddings de las sinopsis de las películas
embeddings = []

for plot in df['Processed_Plot']:
    plot_embedding = []
    for word in plot.split():
        if word in model.wv.key_to_index:
            plot_embedding.append(model.wv[word])
    if plot_embedding:
        embeddings.append(np.mean(plot_embedding, axis=0))

# Calcular la similitud coseno entre todos los pares de embeddings
similarity_matrix = cosine_similarity(embeddings, embeddings)

# Imprimir la matriz de similitud
print("Matriz de Similitud:")
print(similarity_matrix)

Matriz de Similitud:
[[1.         0.9132058  0.90523493 ... 0.79589355 0.86068547 0.7772419 ]
 [0.9132058  0.9999999  0.9360242  ... 0.80775094 0.87228    0.811415  ]
 [0.90523493 0.9360242  1.         ... 0.80160177 0.88752306 0.83203983]
 ...
 [0.79589355 0.80775094 0.80160177 ... 1.         0.91801023 0.92820644]
 [0.86068547 0.87228    0.88752306 ... 0.91801023 1.         0.93712187]
 [0.7772419  0.81141484 0.83203995 ... 0.92820644 0.93712187 1.        ]]


In [19]:
print("Tamaño de similarity_matrix:", similarity_matrix.shape)

Tamaño de similarity_matrix: (34886, 34886)


## 4. Recomendar peliculas a partir de su nombre y de la similitud coseno entre los embedings de cada sinopsis.

In [34]:
def recomendar_peliculas(idx_pelicula, similarity_matrix, df, top_n=20):
    # Obtener las similitudes de la película de entrada con todas las demás películas
    sim_scores = list(enumerate(similarity_matrix[idx_pelicula]))
    #print(sim_scores)

    # Ordenar las similitudes
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Obtener los índices de las películas más similares (excluyendo la película de entrada)
    sim_scores = sim_scores[1:top_n+1]  # Excluyendo la película de entrada

    # Obtener los índices y títulos de las películas recomendadas
    movie_indices = [i[0] for i in sim_scores]
    recommended_movies = df.iloc[movie_indices]['Title'].values

    return recommended_movies

In [41]:
idx_pelicula_entrada = 60  
peliculas_recomendadas = recomendar_peliculas(idx_pelicula_entrada, similarity_matrix, df)

print(f"Películas recomendadas para la película de : {df.loc[idx_pelicula_entrada,'Title']}:")
for idx, movie in enumerate(peliculas_recomendadas, 1):
    print(f"{idx}. {movie}")

Películas recomendadas para la película de : The Telephone Girl and the Lady:
1. To Catch a Thief
2. To Catch a Thief
3. City Lights
4. Who's That Girl
5. Half a Sinner
6. Vaseegaran, Priyamani
7. Make Mine Mink
8. Boston Quackie
9. Bab El Hadid (Cairo Station, The Iron Gate)
10. Jewel Robbery
11. Union Depot
12. The Lone Wolf Spy Hunt
13. Young and Innocent
14. The 39 Steps
15. Penelope
16. The Beggar's Opera
17. Meet the Wildcat
18. Number Seventeen
19. Gideon's Day
20. The Devil's Brother


## CASO 2

Para clasificar las revisiones de películas como positivas o negativas, primero realizaría un preprocesamiento de texto para limpiar y normalizar los datos, lo que implica eliminar signos de puntuación, convertir el texto a minúsculas y eliminar palabras irrelevantes (stopwords). Luego, utilizaría TF-IDF de técnicas de procesamiento de lenguaje natural (NLP) para extraer características relevantes de las revisiones. A continuación, dividiría los datos en conjuntos de entrenamiento y prueba para evaluar el rendimiento del modelo. Probaría varios algoritmos de clasificación como Naive Bayes, Support Vector Machines (SVM) o modelos de aprendizaje profundo como redes neuronales. Entrenaría los modelos utilizando el conjunto de entrenamiento y ajustaría los hiperparámetros utilizando validación cruzada. Finalmente, evaluaría el rendimiento del modelo en el conjunto de prueba utilizando métricas como precisión, recall y F1-score para determinar su efectividad en la clasificación de revisiones como positivas o negativas. Dependiendo del rendimiento, ajustaría el modelo y repetiría el proceso hasta obtener resultados satisfactorios.